name: CI
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run Tests
        run: mvn -B test